name: Sync web resources with StreamX

on:
  workflow_dispatch:
    inputs:
      publish_all_webresources:
        description: "Publish all, pattern included webresources to StreamX"
        required: false
        type: boolean
        default: false

  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  sync-pr-with-streamx:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run sync with StreamX
        uses: streamx-hub/streamx-common-github-actions/.github/actions/connector-github@v1
        env:
          STREAMX_CONNECTION_SOCKET_TIMEOUT: 3000
        with:
          source-provider: PullRequestDiffSourceProvider
          streamx-ingestion-url: ${{ vars.STREAMX_INGESTION_URL }}
          streamx-ingestion-token: ${{ secrets.STREAMX_INGESTION_GH_TOKEN }}
          event-type: "com.streamx.blueprints.web-resource.published.v1"
          deleted-event-type: "com.streamx.blueprints.web-resource.unpublished.v1"
          event-data: '{"type":"web-resource/static"}'
          include-patterns: ${{ vars.STREAMX_INGESTION_INCLUDES }}

  sync-all-with-streamx:
    if: github.event_name == 'workflow_dispatch' && inputs.publish_all_webresources == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run full sync with StreamX
        uses: streamx-hub/streamx-common-github-actions/.github/actions/connector-github@v1
        env:
          STREAMX_CONNECTION_SOCKET_TIMEOUT: 3000
        with:
          source-provider: BatchSourceProvider
          streamx-ingestion-url: ${{ vars.STREAMX_INGESTION_URL }}
          streamx-ingestion-token: ${{ secrets.STREAMX_INGESTION_GH_TOKEN }}
          event-type: 'com.streamx.blueprints.web-resource.published.v1'
          workspace: ${{ github.workspace }}
          event-data: '{"type": "web-resource/static"}'
          include-patterns: ${{ vars.STREAMX_INGESTION_INCLUDES }}

  schedule-index-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up homebrew
        uses: 'Homebrew/actions/setup-homebrew@master'

      - name: Install and setup StreamX
        run: |
          brew install streamx-com/preview-tap/streamx
          streamx settings set streamx.ingestion.url ${{ vars.STREAMX_INGESTION_URL }}
          streamx settings set streamx.ingestion.auth-token ${{ secrets.STREAMX_INGESTION_GH_TOKEN }}

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Generate and publish stream
        shell: bash
        env:
          EDS_URL: ${{ vars.EDS_DOMAIN_URL }}
          STREAMX_TOKEN: ${{ secrets.STREAMX_INGESTION_GH_TOKEN }}
        run: |
          set -e

          echo "Generating event stream..."

          targets=()

          while IFS= read -r line; do
            targets+=("$line")
          done < <(
            yq e '.. | select(has("target")) | .target' \
            ./helix-query.yaml
          )

          stream_file="stream.jsonl"
          > "$stream_file"

          for target in "${targets[@]}"; do
            if [ -z "$target" ]; then
              continue
            fi

            clean="${target#/}"
            filename=$(echo "$clean" | sed 's/\//_/g')

            uuid=$(uuidgen)
            time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

            url="${EDS_URL}/${filename}"

            cat >> "$stream_file" <<EOF
          {
            "specversion": "1.0",
            "id": "${uuid}",
            "source": "github",
            "type": "com.streamx.blueprints.download.schedule.v1",
            "datacontenttype": "application/json",
            "subject": "${filename}",
            "time": "${time}",
            "data": {
              "url": "${url}",
              "emitKey": "${filename}",
              "emittedPageType": "",
              "emittedWebResourceType": "web-resource/static",
              "emittedAssetType": ""
            }
          }
          EOF
          
          done
          
          echo "Publishing stream to StreamX..."
          
          streamx publish stream "$stream_file"
          
          echo "Done."